"""add celery_task_id to generations

Revision ID: eb1a8e22f750
Revises: 860ab8b17c19
Create Date: 2026-07-02 21:21:21.560163
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1a8e22f750'
down_revision: Union[str, None] = '860ab8b17c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'celery_task_id')
    # ### end Alembic commands ###
